name: C/C++ CI (Multi-Platform)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4

    - name: Setup Windows Tools
      if: matrix.os == 'windows-latest'
      run: choco install cmake -y

    - name: Setup MSVC (Windows)
      if: matrix.os == 'windows-latest'
      uses: actions/setup-msvc@v1
      with:
        vs-version: '2022'

    - name: Install Dependencies (macOS/Linux)
      if: matrix.os != 'windows-latest'
      run: |
        if [[ "${{ matrix.os }}" == "macos-latest" ]]; then
          brew install cmake  # macOS 用 Homebrew
        else
          sudo apt-get install -y cmake  # Ubuntu
        fi

    - name: Configure
      run: |
        if [[ "${{ matrix.os }}" == "windows-latest" ]]; then
          cmake -B build -S .
        else
          ./configure
        fi

    - name: Build
      run: |
        if [[ "${{ matrix.os }}" == "windows-latest" ]]; then
          cmake --build build
        else
          make
        fi
