name: C/C++ CI (Multi-Platform)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4

    - name: Install CMake
      run: |
        if [[ "${{ matrix.os }}" == "windows-latest" ]]; then
          choco install cmake -y
        elif [[ "${{ matrix.os }}" == "macos-latest" ]]; then
          brew install cmake
        else
          sudo apt-get update && sudo apt-get install -y cmake
        fi
        shell: bash
        
    - name: Configure with CMake
      run: cmake -B build -S .
      shell: bash

    - name: Build with CMake
      run: cmake --build build
      shell: bash
